name: Expo EAS Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install
      - name: Build Android
        env:
          EXPO_TOKEN: mNmp-o04381I9E2GN2WSp76iiqLVuw6bZ2etu2RF
        run: eas build --platform android --non-interactive --profile production
